import "./index";
import { associateItemIdentifier } from "./item_identifier";
import { associateLoginLog } from "./login_log";
import { associateOrder } from "./order";
import { associateBin } from "./bin";
import { associateOrderIdentifier } from "./order_identifier";
import { associateOrderItem } from "./order_item";
import { associateOrganization } from "./organization";
import { associateProduct } from "./product";
import { associateProductGroup } from "./product_group";
import { associateProductIdentifier } from "./product_identifier";
import { associateProductItem } from "./product_item";
import { associateProductSpec } from "./product_spec";
import { associateTask } from "./task";
import { associateTaskGroup } from "./task_group";
import { associateTaskLog } from "./task_log";
import { associateTaskRelationship } from "./task_relationship";
import { associateUser } from "./user";
import { associateWorkflow } from "./workflow";

associateItemIdentifier();
associateLoginLog();
associateOrderIdentifier();
associateOrderItem();
associateOrder();
associateOrganization();
associateProduct();
associateProductGroup();
associateProductIdentifier();
associateProductItem();
associateProductSpec();
associateTask();
associateTaskGroup();
associateTaskLog();
associateTaskRelationship();
associateUser();
associateWorkflow();
associateBin();
