export enum ErrorCodes {
	TIMEOUT = "TIMEOUT",
	UNKNOWN = "UNKNOWN",
	IPC_ERROR = "IPC_ERROR",
	INVALID_REQUEST = "INVALID_REQUEST",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	INTERNAL_ERROR = "INTERNAL_ERROR",
	USER_INCORRECT_PASSWORD = "USER_INCORRECT_PASSWORD",
	NO_TOKEN_PROVIDED = "NO_TOKEN_PROVIDED",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    USER_NOT_AUTHORIZED = "USER_NOT_AUTHORIZED",
	WEAK_PASSWORD = "WEAK_PASSWORD",
}
